// Code generated by protoc-gen-goten-access
// Service: CellularApi
// DO NOT EDIT!!!

package cellular_api_access

import (
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"

	contract_access "github.com/cloudwan/edgelq-sdk/cellular-api/access/v1/contract"
	sim_card_access "github.com/cloudwan/edgelq-sdk/cellular-api/access/v1/sim_card"
	sim_card_stock_access "github.com/cloudwan/edgelq-sdk/cellular-api/access/v1/sim_card_stock"
	cellular_api_client "github.com/cloudwan/edgelq-sdk/cellular-api/client/v1/cellular_api"
	contract "github.com/cloudwan/edgelq-sdk/cellular-api/resources/v1/contract"
	sim_card "github.com/cloudwan/edgelq-sdk/cellular-api/resources/v1/sim_card"
	sim_card_stock "github.com/cloudwan/edgelq-sdk/cellular-api/resources/v1/sim_card_stock"
)

type CellularApiApiAccess interface {
	gotenresource.Access

	contract.ContractAccess
	sim_card.SimCardAccess
	sim_card_stock.SimCardStockAccess
}

type apiCellularApiAccess struct {
	gotenresource.Access

	contract.ContractAccess
	sim_card.SimCardAccess
	sim_card_stock.SimCardStockAccess
}

func NewApiAccess(client cellular_api_client.CellularApiClient) CellularApiApiAccess {

	contractAccess := contract_access.NewApiContractAccess(client)
	simCardAccess := sim_card_access.NewApiSimCardAccess(client)
	simCardStockAccess := sim_card_stock_access.NewApiSimCardStockAccess(client)

	return &apiCellularApiAccess{
		Access: gotenresource.NewCompositeAccess(

			contract.AsAnyCastAccess(contractAccess),
			sim_card.AsAnyCastAccess(simCardAccess),
			sim_card_stock.AsAnyCastAccess(simCardStockAccess),
		),

		ContractAccess:     contractAccess,
		SimCardAccess:      simCardAccess,
		SimCardStockAccess: simCardStockAccess,
	}
}
