// Code generated by protoc-gen-goten-object
// File: edgelq/limits/proto/v1alpha2/limit_pool_custom.proto
// DO NOT EDIT!!!

package limit_pool_client

import (
	"fmt"
	"sort"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/fieldmaskpb"

	gotenobject "github.com/cloudwan/goten-sdk/runtime/object"
)

// proto imports
import (
	limit_pool "github.com/cloudwan/edgelq-sdk/limits/resources/v1alpha2/limit_pool"
)

// ensure the imports are used
var (
	_ = new(fmt.Stringer)
	_ = new(sort.Interface)

	_ = new(proto.Message)
	_ = fieldmaskpb.FieldMask{}

	_ = new(gotenobject.FieldPath)
)

// make sure we're using proto imports
var (
	_ = &limit_pool.LimitPool{}
)

func (o *MigrateLimitPoolSourceRequest) GotenObjectExt() {}

func (o *MigrateLimitPoolSourceRequest) MakeFullFieldMask() *MigrateLimitPoolSourceRequest_FieldMask {
	return FullMigrateLimitPoolSourceRequest_FieldMask()
}

func (o *MigrateLimitPoolSourceRequest) MakeRawFullFieldMask() gotenobject.FieldMask {
	return FullMigrateLimitPoolSourceRequest_FieldMask()
}

func (o *MigrateLimitPoolSourceRequest) MakeDiffFieldMask(other *MigrateLimitPoolSourceRequest) *MigrateLimitPoolSourceRequest_FieldMask {
	if o == nil && other == nil {
		return &MigrateLimitPoolSourceRequest_FieldMask{}
	}
	if o == nil || other == nil {
		return FullMigrateLimitPoolSourceRequest_FieldMask()
	}

	res := &MigrateLimitPoolSourceRequest_FieldMask{}
	if o.GetName().String() != other.GetName().String() {
		res.Paths = append(res.Paths, &MigrateLimitPoolSourceRequest_FieldTerminalPath{selector: MigrateLimitPoolSourceRequest_FieldPathSelectorName})
	}
	return res
}

func (o *MigrateLimitPoolSourceRequest) MakeRawDiffFieldMask(other gotenobject.GotenObjectExt) gotenobject.FieldMask {
	return o.MakeDiffFieldMask(other.(*MigrateLimitPoolSourceRequest))
}

func (o *MigrateLimitPoolSourceRequest) Clone() *MigrateLimitPoolSourceRequest {
	if o == nil {
		return nil
	}
	result := &MigrateLimitPoolSourceRequest{}
	if o.Name == nil {
		result.Name = nil
	} else if data, err := o.Name.ProtoString(); err != nil {
		panic(err)
	} else {
		result.Name = &limit_pool.Reference{}
		if err := result.Name.ParseProtoString(data); err != nil {
			panic(err)
		}
	}
	return result
}

func (o *MigrateLimitPoolSourceRequest) CloneRaw() gotenobject.GotenObjectExt {
	return o.Clone()
}

func (o *MigrateLimitPoolSourceRequest) Merge(source *MigrateLimitPoolSourceRequest) {
	if source.GetName() != nil {
		if data, err := source.GetName().ProtoString(); err != nil {
			panic(err)
		} else {
			o.Name = &limit_pool.Reference{}
			if err := o.Name.ParseProtoString(data); err != nil {
				panic(err)
			}
		}
	} else {
		o.Name = nil
	}
}

func (o *MigrateLimitPoolSourceRequest) MergeRaw(source gotenobject.GotenObjectExt) {
	o.Merge(source.(*MigrateLimitPoolSourceRequest))
}
