// Code generated by protoc-gen-goten-resource
// Resource: Secret
// DO NOT EDIT!!!

package secret

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	gotenobject "github.com/cloudwan/goten-sdk/runtime/object"
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"
	"github.com/cloudwan/goten-sdk/types/watch_type"
)

// proto imports
import (
	project "github.com/cloudwan/edgelq-sdk/secrets/resources/v1alpha2/project"
	meta "github.com/cloudwan/goten-sdk/types/meta"
)

// ensure the imports are used
var (
	_ = new(context.Context)

	_ = codes.Internal
	_ = status.Status{}

	_ = watch_type.WatchType_STATEFUL
	_ = new(gotenobject.FieldPath)
	_ = new(gotenresource.ListQuery)
)

// make sure we're using proto imports
var (
	_ = &project.Project{}
	_ = &meta.Meta{}
)

type SecretAccess interface {
	GetSecret(context.Context, *GetQuery, ...gotenresource.GetOption) (*Secret, error)
	BatchGetSecrets(context.Context, []*Reference, ...gotenresource.BatchGetOption) error
	QuerySecrets(context.Context, *ListQuery, ...gotenresource.QueryOption) (*QueryResultSnapshot, error)
	WatchSecret(context.Context, *GetQuery, func(*SecretChange) error) error
	WatchSecrets(context.Context, *WatchQuery, func(*QueryResultChange) error) error
	SaveSecret(context.Context, *Secret, ...gotenresource.SaveOption) error
	DeleteSecret(context.Context, *Reference, ...gotenresource.DeleteOption) error
}

type anyCastAccess struct {
	SecretAccess
}

func AsAnyCastAccess(access SecretAccess) gotenresource.Access {
	return &anyCastAccess{SecretAccess: access}
}

func (a *anyCastAccess) Get(ctx context.Context, q gotenresource.GetQuery, opts ...gotenresource.GetOption) (gotenresource.Resource, error) {
	if asSecretQuery, ok := q.(*GetQuery); ok {
		return a.GetSecret(ctx, asSecretQuery, opts...)
	}
	return nil, status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected Secret, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Query(ctx context.Context, q gotenresource.ListQuery, opts ...gotenresource.QueryOption) (gotenresource.QueryResultSnapshot, error) {
	if asSecretQuery, ok := q.(*ListQuery); ok {
		return a.QuerySecrets(ctx, asSecretQuery, opts...)
	}
	return nil, status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected Secret, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Search(ctx context.Context, q gotenresource.SearchQuery, opts ...gotenresource.QueryOption) (gotenresource.QueryResultSnapshot, error) {
	return nil, status.Errorf(codes.Internal, "Search is not available for Secret")
}

func (a *anyCastAccess) Watch(ctx context.Context, q gotenresource.GetQuery, cb func(ch gotenresource.ResourceChange) error) error {
	if asSecretQuery, ok := q.(*GetQuery); ok {
		return a.WatchSecret(ctx, asSecretQuery, func(change *SecretChange) error {
			return cb(change)
		})
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected Secret, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) WatchQuery(ctx context.Context, q gotenresource.WatchQuery, cb func(ch gotenresource.QueryResultChange) error) error {
	if asSecretQuery, ok := q.(*WatchQuery); ok {
		return a.WatchSecrets(ctx, asSecretQuery, func(change *QueryResultChange) error {
			return cb(change)
		})
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected Secret, got: %s",
		q.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Save(ctx context.Context, res gotenresource.Resource, opts ...gotenresource.SaveOption) error {
	if asSecretRes, ok := res.(*Secret); ok {
		return a.SaveSecret(ctx, asSecretRes, opts...)
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected Secret, got: %s",
		res.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) Delete(ctx context.Context, ref gotenresource.Reference, opts ...gotenresource.DeleteOption) error {
	if asSecretRef, ok := ref.(*Reference); ok {
		return a.DeleteSecret(ctx, asSecretRef, opts...)
	}
	return status.Errorf(codes.Internal,
		"Unrecognized descriptor, expected Secret, got: %s",
		ref.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
}

func (a *anyCastAccess) BatchGet(ctx context.Context, toGet []gotenresource.Reference, opts ...gotenresource.BatchGetOption) error {
	secretRefs := make([]*Reference, 0, len(toGet))
	for _, ref := range toGet {
		if asSecretRef, ok := ref.(*Reference); !ok {
			return status.Errorf(codes.Internal,
				"Unrecognized descriptor, expected Secret, got: %s",
				ref.GetResourceDescriptor().GetResourceTypeName().FullyQualifiedTypeName())
		} else {
			secretRefs = append(secretRefs, asSecretRef)
		}
	}
	return a.BatchGetSecrets(ctx, secretRefs, opts...)
}

func (a *anyCastAccess) GetResourceDescriptors() []gotenresource.Descriptor {
	return []gotenresource.Descriptor{
		GetDescriptor(),
	}
}
