// Code generated by protoc-gen-goten-resource
// Resource: LogConditionTemplate
// DO NOT EDIT!!!

package log_condition_template

import (
	googlefieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"

	"github.com/cloudwan/goten-sdk/types/view"
)

// proto imports
import (
	document "github.com/cloudwan/edgelq-sdk/alerting/resources/v1/document"
	log_condition "github.com/cloudwan/edgelq-sdk/alerting/resources/v1/log_condition"
	policy_template "github.com/cloudwan/edgelq-sdk/alerting/resources/v1/policy_template"
	meta "github.com/cloudwan/goten-sdk/types/meta"
)

// ensure the imports are used
var (
	_ = googlefieldmaskpb.FieldMask{}

	_ = view.View_UNSPECIFIED
)

// make sure we're using proto imports
var (
	_ = &document.Document{}
	_ = &log_condition.LogCondition{}
	_ = &policy_template.PolicyTemplate{}
	_ = &meta.Meta{}
)

func ResourceViewFieldMask(viewName view.View, extraMask *LogConditionTemplate_FieldMask) *LogConditionTemplate_FieldMask {
	protoFieldMask := &googlefieldmaskpb.FieldMask{}

	switch viewName {
	case view.View_UNSPECIFIED:
		return extraMask
	case view.View_FULL:
		return nil
	case view.View_BASIC:
		protoFieldMask.Paths = append(protoFieldMask.Paths, "name", "display_name", "spec_template.query.filter", "spec_template.query.trigger")
		break
	case view.View_DETAIL:
		protoFieldMask.Paths = append(protoFieldMask.Paths, "name", "display_name", "description", "supporting_docs", "spec_template.query.filter", "spec_template.query.trigger", "spec_template.group_by_labels")
		break
	case view.View_NAME:
		protoFieldMask.Paths = append(protoFieldMask.Paths, "name", "display_name")
		break
	default:
		return extraMask
	}
	if extraMask != nil {
		protoFieldMask.Paths = append(protoFieldMask.Paths, extraMask.ToProtoFieldMask().Paths...)
	}
	res := &LogConditionTemplate_FieldMask{}
	_ = res.FromProtoFieldMask(protoFieldMask)
	return res
}
